# Generated by Django 3.2.7 on 2021-09-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hook_test',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
